apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: o3ci95u98-python 
  janus-idp.io/tekton: o3ci95u98-python
  backstage.io/kubernetes-id: o3ci95u98-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o3ci95u98-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml